version: "3"
services:
  db:
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

  api:
    image: piotrostr/premiere
    build: .
    env_file: .env
    depends_on: [db]
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
