apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
 name: letsencrypt-prod
spec:
 acme:
   server: https://acme-v02.api.letsencrypt.org/directory
   email: piotr.jp.ostrowski@gmail.com
   privateKeySecretRef:
     name: letsencrypt-prod
   solvers:
   - http01:
       ingress:
         class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-premiere
  namespace: default
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.premiere.sh
      secretName: ingress-premiere-tls
  rules:
    - host: api.premiere.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: premiere-api-port
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: premiere-api-port
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: metadata-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: premiere-api
spec:
  selector:
    matchLabels:
      name: premiere-api
  replicas: 3
  template:
      metadata:
        labels:
          name: premiere-api
      spec:
        containers:
          - name: premiere-api
            image: docker.io/piotrostr/premiere
            env:
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-secrets
                    key: password
                    optional: false
              - name: POSTGRES_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: postgres-secrets
                    key: user
                    optional: false
              - name: POSTGRES_HOST
                value: db
            ports:
              - containerPort: 80
        imagePullSecrets:
          - name: regcred
        restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: db-port
  labels:
    name: db-port
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  labels:
    name: db-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "2Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      name: db
  replicas: 1
  template:
      metadata:
        labels:
          name: db
      spec:
        containers:
          - name: db-container
            image: postgres
            ports:
              - containerPort: 5432
            env:
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-secrets
                    key: password
                    optional: false
              - name: POSTGRES_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: postgres-secrets
                    key: user
                    optional: false
            volumeMounts:
              - mountPath: /var/lib/postgresql/data
                name: db-storage
        volumes:
          - name: db-storage
            persistentVolumeClaim:
              claimName: db-pvc
