apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: premiere-backend
build:
  artifacts:
  - image: piotrostr/premiere
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - manifest.yaml
