apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: api
build:
  artifacts:
  - image: piotrostr/premiere
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - manifest.yml
