name: CI/CD
on: ["push", "pull_request"]
env:
  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-20.04

    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
      
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup
      uses: actions/setup-python@v3

    - name: Install Deps
      run: pip install -r requirements.txt

    - name: Run Tests
      run: pytest --cov=./ --cov-report=xml

    - name: Codecov
      uses: codecov/codecov-action@master
      with:
        verbose: true
