
name: CI/CD

on:
  push:
    branches:
      - master

env:
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_USERNAME: postgres
  POSTGRES_HOST: db

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    environment: test
    steps: 
    - name: Checkout
      uses: actions/checkout@v2

    - name: Populate env file
      run: |
        touch .env
        echo POSTGRES_HOST=${{ env.POSTGRES_HOST }} >> .env
        echo POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }} >> .env
        echo POSTGRES_USERNAME=${{ env.POSTGRES_USERNAME }} >> .env

    - name: Build container and run tests
      id: run-tests
      run: |
        docker-compose build
        docker-compose run api pytest
