
name: CI/CD

on:
  push:
    branches:
      - master

env:
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_USERNAME: postgres
  POSTGRES_HOST: db

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-python@v3

    - name: Install Deps
      run: pip install -r requirements.txt

    - name: Run Tests
      run: pytest --cov=./ --cov-report=xml

    - name: Codecov
      uses: codecov/codecov-action@master
      with:
        verbose: true
